In [2]:
import pandas as pd

df = pd.read_csv('../data/insider_threat_clean_dataset.csv')
print(df.shape)
df.head()

(118614, 22)

,employee_department,employee_campus,employee_position,employee_seniority_years,is_contractor,employee_classification,has_foreign_citizenship,has_criminal_record,has_medical_history,employee_origin_country,...,total_files_burned,burned_from_other,is_abroad,trip_day_number,hostility_country_level,num_entries,num_unique_campus,late_exit_flag,entry_during_weekend,is_malicious
0,Engineering Department,Campus C,Design Engineer,22,0,2,0,0,0,Georgia,...,4,0,0,0.0,0,1,1,0,1,0
1,Engineering Department,Campus C,Design Engineer,22,0,2,0,0,0,Georgia,...,0,0,0,0.0,0,1,1,0,0,0
2,Engineering Department,Campus C,Design Engineer,22,0,2,0,0,0,Georgia,...,2,0,0,0.0,0,1,1,0,0,0
3,Engineering Department,Campus C,Design Engineer,22,0,2,0,0,0,Georgia,...,0,0,0,0.0,0,1,1,0,0,0
4,Engineering Department,Campus C,Design Engineer,22,0,2,0,0,0,Georgia,...,0,0,0,0.0,0,0,0,0,0,0

In [3]:
print(df.isnull().sum())

employee_department            0
employee_campus                0
employee_position              0
employee_seniority_years       0
is_contractor                  0
employee_classification        0
has_foreign_citizenship        0
has_criminal_record            0
has_medical_history            0
employee_origin_country        0
total_printed_pages            0
num_printed_pages_off_hours    0
total_files_burned             0
burned_from_other              0
is_abroad                      0
trip_day_number                0
hostility_country_level        0
num_entries                    0
num_unique_campus              0
late_exit_flag                 0
entry_during_weekend           0
is_malicious                   0
dtype: int64

In [4]:
print(df['is_malicious'].value_counts())
print(df['is_malicious'].value_counts(normalize=True))

is_malicious
0    112228
1      6386
Name: count, dtype: int64
is_malicious
0    0.946161
1    0.053839
Name: proportion, dtype: float64

In [5]:
columns_to_drop = ['late_exit_flag', 'trip_day_number', 'has_medical_history', 'employee_origin_country']
df = df.drop(columns=columns_to_drop)
print("Remaining columns:", df.columns.tolist())

Remaining columns: ['employee_department', 'employee_campus', 'employee_position', 'employee_seniority_years', 'is_contractor', 'employee_classification', 'has_foreign_citizenship', 'has_criminal_record', 'total_printed_pages', 'num_printed_pages_off_hours', 'total_files_burned', 'burned_from_other', 'is_abroad', 'hostility_country_level', 'num_entries', 'num_unique_campus', 'entry_during_weekend', 'is_malicious']

In [6]:
from sklearn.preprocessing import LabelEncoder

categorical_cols = ['employee_department', 'employee_campus', 'employee_position']
le = LabelEncoder()

for col in categorical_cols:
    df[col] = le.fit_transform(df[col])

df.head()

,employee_department,employee_campus,employee_position,employee_seniority_years,is_contractor,employee_classification,has_foreign_citizenship,has_criminal_record,total_printed_pages,num_printed_pages_off_hours,total_files_burned,burned_from_other,is_abroad,hostility_country_level,num_entries,num_unique_campus,entry_during_weekend,is_malicious
0,0,2,15,22,0,2,0,0,0,0,4,0,0,0,1,1,1,0
1,0,2,15,22,0,2,0,0,0,0,0,0,0,0,1,1,0,0
2,0,2,15,22,0,2,0,0,0,0,2,0,0,0,1,1,0,0
3,0,2,15,22,0,2,0,0,1,0,0,0,0,0,1,1,0,0
4,0,2,15,22,0,2,0,0,0,0,0,0,0,0,0,0,0,0

In [7]:
df.to_csv('../data/cleaned_dataset.csv', index=False)
print("Cleaned dataset saved!")
print("Final shape:", df.shape)

Cleaned dataset saved!
Final shape: (118614, 18)